# Generated by Django 3.2 on 2022-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.PositiveIntegerField(),
        ),
    ]
